version: 2
jobs:
  build:
    docker:
      - image: circleci:ruby:2.3.6
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: ogs build essentials 
          command: |
           apt-get -y update
      - run: echo "A second hello"
      
 workflows:
    version: 2
    build:
      - build
 
