version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.6
        environment:
         ENV PHANTOM_JS=phantomjs-2.1.1-linux-x86_64
    steps:
      #- checkout
      - run:
          name: Install update and curl 
          command: |
           sudo apt-get -y update
           sudo apt-get install -y curl
      - run:
          name: Install Node Js
          command: |
           sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
           sudo apt-get install -y nodejs
      - run:
         name: Install Chrome 
         command: |
           sudo apt-get install -yes build-essential
           sudo curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
           sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
           #sudo apt-get -y update
           #sudo apt-get -y install google-chrome-stable
        
workflows:
  version: 2
  build-and-test:
    jobs:
     - build
