version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.6
        environment:
         ENV PHANTOM_JS=phantomjs-2.1.1-linux-x86_64
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: ogs build essentials 1
          command: |
           sudo apt-get -y update


 
workflows:
  version: 2
  build-and-test:
    jobs:
     - build
