version: 2
jobs:
  build:
    working_directory: ~/labor-service
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - checkout
     - run: 
         name: Build Process
         command: ls -la
  deploy:
    working_directory: ~/labor-service
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - checkout
     - setup_remote_docker
     # Download and cache dependencies
     - restore_cache:
         keys: 
          - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

     - run: mvn dependency:go-offline
     - save_cache:
         paths:
          - ~/.m2
         key: v1-dependencies-{{ checksum "pom.xml" }}

     - run: mvn -Dmaven.test.skip=true package
     - run:
         name: Run the deploy.sh to remote Machine
         command: |
           ./push_to_ecr.sh
           scp -o  StrictHostKeyChecking=no deploy.sh ubuntu@$AWS_EC2_IP_ADDRESS:/home/ubuntu/labor/deploy.sh
           scp -o  StrictHostKeyChecking=no docker-service.yml ubuntu@$AWS_EC2_IP_ADDRESS:/home/ubuntu/labor/docker-service.yml
           ssh -o StrictHostKeyChecking=no ubuntu@$AWS_EC2_IP_ADDRESS "/home/ubuntu/labor/deploy.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master