version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.6
        environment:
         ENV PHANTOM_JS=phantomjs-2.1.1-linux-x86_64
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: ogs build essentials 
          command: |
           sudo apt-get -y update
           sudo apt-get install -y curl
           sudo apt-get install -y curl
           sudo curl --silent --location https://deb.nodesource.com/setup_4.x | bash -
           sudo apt-get install -y nodejs
           sudo apt-get install -y build-essential
           sudo curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
           sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
           sudo apt-get -y update
           sudo apt-get -y install google-chrome-stable
           sudo apt-get -y install build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
           sudo wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
           sudo tar -xvjf $PHANTOM_JS.tar.bz2
           sudo mv $PHANTOM_JS /usr/local/share
           sudo ln -s /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
 
workflows:
  version: 2
  build-and-test:
    jobs:
     - build
