version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.6
        environment:
         ENV PHANTOM_JS=phantomjs-2.1.1-linux-x86_64
    steps:
      #- checkout
      - run:
          name: ogs build essentials 1
          command: |
           sudo apt-get -y update
           sudo apt-get install -y curl
      - run:
          name: Install Node Js
          command: |
           sudo curl --silent --location https://deb.nodesource.com/setup_4.x | bash -
           sudo apt-get install -y nodejs
 
workflows:
  version: 2
  build-and-test:
    jobs:
     - build
